name = "tokensyber-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "PLAYER_DO", class_name = "PlayerDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PlayerDO"]
